#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
xsetroot -cursor_name left_ptr &

WALLPAPER=/home/steve/Pictures/Wallpapers/cyberpunk2077_001.jpg
feh --bg-fill $WALLPAPER --no-fehbg
~/.config/polybar/launch.sh
wal -i $WALLPAPER -n

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Yes.
bspc config border_width            0
bspc config window_gap              16
bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config pointer_follows_focus   true

